AWSTemplateFormatVersion: 2010-09-09
Description: |
  "author": 
Parameters:
  subnetVPC:
    Description: subnet az to deploy ec2
    Type: String
  

Resources:
  CFInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: JSON # Required
      Description: testing role creation in cf
      ManagedPolicyArns: 
        ManagedPolicyArns
      MaxSessionDuration: Number
      Path: "String"
      PermissionsBoundary: "String"
      Policies: 
        Policies
      RoleName: "String"
      Tags: 
        Tags
  CFInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: CFInstanceProfile
      Path: /
      Roles: # Required
        Roles
  SpecialEc2:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings: 
        - DeviceName: /dev/?
          Ebs:
            VolumeSize: 2
        - DeviceName: /dev/?
          VirtualName: ephemeral0
      CpuOptions:
        CoreCount: Number
        ThreadsPerCore: Number
      CreditSpecification:
        CPUCredits: "Number"
      DisableApiTermination: false
      EbsOptimized: false
      ElasticGpuSpecifications: 
        ElasticGpuSpecifications
      ElasticInferenceAccelerators: 
        ElasticInferenceAccelerators
      EnclaveOptions:
        Enabled: false
      HibernationOptions:
        Configured: false
      HostId: "String"
      HostResourceGroupArn: "String"
      IamInstanceProfile: "String"
      ImageId: "String"
      InstanceInitiatedShutdownBehavior: "String"
      InstanceType: "String"
      Ipv6AddressCount: Number
      Ipv6Addresses: 
        Ipv6Addresses
      KernelId: "String"
      KeyName: "String"
      LaunchTemplate:
        LaunchTemplateId: "String"
        LaunchTemplateName: "String"
        Version: "String"
      LicenseSpecifications: 
        LicenseSpecifications
      Monitoring: String
      NetworkInterfaces: 
        NetworkInterfaces
      PlacementGroupName: "String"
      PrivateDnsNameOptions:
        EnableResourceNameDnsAAAARecord: false
        EnableResourceNameDnsARecord: false
        HostnameType: "String"
      PrivateIpAddress: "false"
      PropagateTagsToVolumeOnCreation: String
      RamdiskId: "String"
      SecurityGroupIds: 
        SecurityGroupIds
      SecurityGroups: 
        SecurityGroups
      SourceDestCheck: false
      SsmAssociations: 
        SsmAssociations
      SubnetId: "String"
      Tags: 
        Tags
      Tenancy: "String"
      UserData: "String"
      Volumes: 
        Volumes"
Outputs: